export const CSV_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSbnee5WH6Z8I4GbLrQTgax0uJMDd-8wgLzzB9XOnCUhJ2CY6Xviyhb7B_SAliE9JOTYYJ96JDZMrQX/pub?gid=943065784&output=csv';

export const ND = 'Sin información';

export const fields = {
  timestamp: 'Marca temporal',
  jurisdiccion: 'Indique la jurisdicción a la que pertenece',
  nombre: '1.1. ¿Podría indicar el nombre de dicho espacio?',
  existeConsejo: '¿Existe en la jurisdicción un espacio formal de articulación entre educación, trabajo y producción?',
  anioCreacion: '1.2. ¿En qué año fue creado el Consejo (o instancia equivalente)?',
  tieneNorma: '1.3. ¿Existe un marco normativo que regula la creación y/o funcionamiento del Consejo (o instancia equivalente)?',
  tipoNorma: '1.3.1. ¿Qué tipo de norma regula la creación y/o funcionamiento del Consejo (o instancia equivalente)?',
  nombreNorma: '1.3.2. ¿Podría indicarnos el nombre, número y año de la norma?',
  estadoNorma: '1.3.3.  Indique la situación actual de la principal normativa que regula el Consejo en su jurisdicción:',
  ambito: '1.4. ¿En qué ámbito institucional se inscribe el Consejo?',
  dependencia: '1.4.1. Especifique la dependencia, área u organismo del cual depende directamente dentro de dicho ámbito.',
  nActores: '2.1. ¿Cuántos actores/instituciones (de diferentes ámbitos y sectores de actividad) integran la estructura organizativa del Consejo (o instancia equivalente)?',
  actoresGob: '2.2. ¿Qué actores del ámbito gubernamental participan en el Consejo (o instancia equivalente)?',
  actoresEduc: '2.3. ¿Qué actores del ámbito Educativo-Científico participan en el Consejo (o instancia equivalente)?',
  actoresProd: '2.4. ¿Qué actores del sector Productivo/Empresarial participan en el Consejo (o instancia equivalente)?',
  otrosActores: '2.5. ¿Existen otros actores o ámbitos participantes que no hayan sido mencionados anteriormente?',
  organizacion: '2.6. ¿Cómo está organizado el Consejo (o instancia equivalente)?',
  instanciasTf: '2.7. ¿Existen instancias de trabajo del Consejo (mesas, foros u otras) que se agrupen por territorio o por sector de actividad?',
  cualesInstancias: '2.7.1. ¿Cuáles son dichas instancias de trabajo del Consejo?',
  equipoPerm: '2.8. ¿Cuántas personas integran el equipo de personas permanentes del Consejo (o instancia equivalente)?',
  vinculacionLab: '2.9. ¿Cuál es la modalidad de vinculación laboral de las personas que integran el equipo permanente del Consejo (o instancia equivalente)?',
  categoriaResp: '2.10.  En su rol como responsable del Consejo (o instancia equivalente), ¿cuál es su categoría ocupacional?',
  perfilResp: '2.11. ¿Qué perfil profesional tiene la persona Responsable del Consejo (o instancia equivalente)?',
  tiempoResp: '2.12. ¿Cuánto tiempo lleva como Responsable del Consejo (o instancia equivalente)?',
  funcionesPpal: '3.1. ¿Cuáles son las funciones principales que desarrolla el Consejo (o instancia equivalente)?',
  funcionesFrecuentes: '3.2. Seleccione las funciones que el Consejo (o instancia equivalente) desarrolla con mayor frecuencia.',
  frecuenciaReun: '3.3. ¿Con qué frecuencia se reúne el Consejo (o instancia equivalente)?',
  modalidadReun: '3.3.1. ¿Cómo se desarrollan las reuniones?',
  participacion: '3.4. En el último año, aproximadamente, ¿qué cantidad de instituciones o entidades participaron en mesas de trabajo, foros o instancias similares?',
  difusion: '3.3. ¿El Consejo (o instancia equivalente) realiza acciones de difusión o comunicación de sus actividades y/o acuerdos?',
  web: '3.3.1.  Página web institucional',
  boletin: '3.3.2. Boletín, periódico o newsletter propio',
  rrss: '3.3.3.  Redes Sociales (Facebook, Instagram, otros)',
  twitter: '3.3.4. X (Ex Twitter)',
  medios: '3.3.5. Medios de comunicación (prensa escrita, radial o audiovisual)',
  otrosCanales: '3.3.6. Otros medios o canales de difusión no mencionados',
  tipoAcuerdos: '3.4. ¿Qué tipo de acuerdos o resultados se han alcanzado en el marco del Consejo (o instancia equivalente)?',
  formalizacion: '3.5. ¿De qué modo quedaron formalizados o registrados esos acuerdos o resultados?',
  acuerdosRec: '3.6. Mencione hasta tres acuerdos o resultados relevantes alcanzados recientemente por el Consejo.',
  sectorProd: '4.1. ¿Con qué actores del sector productivo se vincula?',
  actoresLab: '4.2. ¿Con qué actores laborales se vincula?',
  otrosSectores: '4.3. ¿Existen vínculos con otros sectores?',
  cualesSectores: '4.4.1. ¿Con cuáles otros sectores se vincula?',
  tipoAcciones: '4.5. ¿Qué tipo de acciones o actividades se desarrollan en el marco de estas articulaciones?',
  caracterizVinc: '4.6. ¿Cómo se caracterizan los vínculos que establece el Consejo (o instancia equivalente) con los actores mencionados?',
  fortalecer: '4.7.  ¿Con qué actores considera que sería relevante fortalecer o desarrollar vínculos que actualmente no existen?',
  rolEtp: '5.1. ¿Qué rol tiene el Consejo (o instancia equivalente) en relación con la ETP?',
  actoresPp: '5.2.  ¿Qué actores participan, a través del Consejo (o instancia equivalente), en el desarrollo de las prácticas profesionalizantes?',
  comentarios: '6.1. ¿Quisiera agregar algún comentario en relación al funcionamiento actual del Consejo (o instancia equivalente)?',
  fortalezas: '6.2. ¿Cuáles considera que son las principales fortalezas en relación al funcionamiento actual del Consejo  (o instancia equivalente)?',
  dificultades: '6.3. ¿Cuáles considera que son las principales dificultades identificadas en relación al funcionamiento actual del Consejo (o instancia equivalente)?',
  documentacion: '6.4 ¿Desea compartir documentación relevante o de interés sobre el Consejo?',
  archivoDoc: 'Adjuntar archivo.',
  enlaceDoc: 'Enlace de acceso a la documentación.'
};
